### ISSUE TITLE
Adding MELPA?

### ISSUE THREAD

**Issue by conao3** [alphapapa/melpa-stats#1]
Hi!
This package seems very useful and I want to use it.
Do you have a plan to add this package to MELPA?

**Comment by alphapapa** [comment]
Hi,

I probably won't add it to MELPA myself, because I don't want to offer support for it.  It's just something I whipped up when I needed it.  If it's useful to other people also, that's good.

If you want something similar that's in MELPA, I think Jonas Bernoulli's `epkg` package provides some similar tools.

**Comment by conao3** [comment]
OK, and also thanks good pointer to `epkg`.
